---
- name: Restart samba
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - smbd
    - nmbd
    - winbind

- name: Restart wazuh-agent
  ansible.builtin.systemd:
    name: wazuh-agent
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
    daemon_reload: true
