---
- name: Restart wazuh-agent
  ansible.builtin.systemd:
    name: wazuh-agent
    state: restarted

- name: Restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
